# Generated by Django 6.0 on 2025-12-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.CharField(editable=False, help_text='Unique identifier for the paste', max_length=22, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The text content of the paste')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when paste was created')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiration timestamp (TTL)', null=True)),
                ('max_views', models.IntegerField(blank=True, help_text='Optional maximum number of views allowed', null=True)),
                ('view_count', models.IntegerField(default=0, help_text='Number of times paste has been viewed via API')),
            ],
            options={
                'verbose_name': 'Paste',
                'verbose_name_plural': 'Pastes',
                'db_table': 'pastes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='paste_expires_idx'), models.Index(fields=['created_at'], name='paste_created_idx')],
            },
        ),
    ]
